Add nested vertical list
IMGIITRoorkee/chakra-library pull request #231
Opened 2022-05-09 13:00 UTC by mrstark14

2022-05-09 14:00 UTC, ParitoshKabra commented on test/components/nested-vertical-list.html
> +                    <div class="vertical-list-nest-content ui one-liner-captions" id="adminpos" onclick="content_click(this.id)">Administrative Positions</div>
There is no need of a vertical-list-line class, just target the ```hr``` tag as a children of vertical-list

2022-05-09 14:01 UTC, ParitoshKabra commented on test/components/nested-vertical-list.html
> +                    <div class="vertical-list-nest-content ui one-liner-captions" id="profbg" onclick="content_click(this.id)">Professional Background</div>
No need of `vertical-list-nest-content` as well, reasons are same as for hr tag

2022-05-09 14:01 UTC, ParitoshKabra commented on test/components/nested-vertical-list.html
> +                <div class="vertical-list-head ui sub-heading" id="1" onclick="head_click(this.id)">Biosketch</div>
Same here

2022-05-09 14:02 UTC, ParitoshKabra commented on test/components/nested-vertical-list.html
> +                <div class="vertical-list-nest">
Let's discuss about this, do we really need this class as well? can't we target divs directly as `.vertical-list > div` ? @mrstark14 , also @ktg-123 @saurabhhere @ayu023ban  PTAL

2022-05-10 02:29 UTC, ParitoshKabra commented
@mrstark14 refresh pe #wali cheej kaam nahi karti, woh fix karde

2022-05-12 18:16 UTC, saurabhhere requested changes

2022-05-12 18:16 UTC, saurabhhere commented on library/javascript/components/nested-vertical-list.js
> +const elements = document.getElementsByClassName('one-liner-captions')
specify the name of elements

2022-05-12 18:16 UTC, saurabhhere commented on library/javascript/components/nested-vertical-list.js
> +const elements1 = document.getElementsByClassName('list-sub-heading')
`element1`?

2022-05-12 18:16 UTC, saurabhhere commented on library/javascript/components/nested-vertical-list.js
> +        console.log('invalid display style');
Remove console

2022-05-12 18:16 UTC, saurabhhere commented on library/css/components/faculty-profile.css
> +.ui.ui.faculty-profile .ui.icon-typography div[onclick]:hover {
Multiple `ui`?

2022-05-12 18:16 UTC, saurabhhere commented on library/css/components/faculty-profile.css
> +  max-height: 100px;
why in `px` use `rem`

2022-05-12 18:16 UTC, saurabhhere commented on library/css/components/nested-vertical-list.css
> +.vertical-list-head {
Try to use more selective css selectors using `>`

2022-05-12 18:16 UTC, saurabhhere commented on library/css/components/nested-vertical-list.css
> +.vertical-list {
More selective css selector, same name can be used by someone else also in other components

2022-05-12 18:16 UTC, saurabhhere commented on library/javascript/components/nested-vertical-list.js
> +    if (element1.length != 0) {
I guess we can use `!==` here?

2022-05-12 18:16 UTC, saurabhhere commented on library/css/components/nested-vertical-list.css
> +    .vertical-list {
More selective in the whole css file

2022-05-12 18:22 UTC, saurabhhere commented
@mrstark14 Around `1300px` pr horizontal scroll aa rha hai meri, I guess second container ki wajah se aa raha, vo bhi dekh lena

2022-05-13 05:21 UTC, merged